name: Main Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: v15.0.1
    - run: npm install
    - run: npm run build:windows
    - run: npm run build:macos
    - run: npm run build:linux
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: dist/*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
