name: Pages Action

on:
  push:
    branches:
    - pages

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: v15.0.1

    - run: npm install

    - run: npm run build:pages

    - uses: actions/upload-artifact@v2
      with:
        name: pages
        path: dist/*

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
